# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{adman}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark"]
  s.date = %q{2010-04-06}
  s.description = %q{Adman makes it easy to publish your application and collaborate with other apps on your local network using Bonjour.}
  s.email = %q{mark@burmis.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/adman.rb",
     "lib/adman/common.rb",
     "lib/adman/dnssd.rb",
     "test/helper.rb",
     "test/test_adman.rb"
  ]
  s.homepage = %q{http://github.com/MarkBennett/adman}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{adman}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Easily share apps using Bonjour}
  s.test_files = [
    "test/helper.rb",
     "test/test_adman.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

